### ISSUE TITLE
Feature Request: Log side texture on top of Log wall connecting parts

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#111]
### What Feature Types Apply to This Request?

Block

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

The wall blocks currently use the log top texture on the top, which makes sense for the posts, but for the connecting parts it looks a bit odd and would look _much_ nicer with the log side texture on the top

As in something like this (although I would also suggest rotating the top log side texture based on the direction the wall is facing):
![2023-05-07_12 23 53](https://user-images.githubusercontent.com/60141811/236689999-c364e724-fab3-4cd8-a21a-e0c40af81954.png)

Rather than this:
![2023-05-07_12 19 48](https://user-images.githubusercontent.com/60141811/236689804-f0a0dbb7-4b09-4916-aba9-28e1023fff59.png)

From above, it might look something like this:
![wallFromAbove](https://user-images.githubusercontent.com/60141811/236690521-d68741ee-8900-4a15-84f1-d446b34e7603.png)

(I apologize if this feature request is a bit confusing, it's hard to word it well while also explaining what I mean)

### Why Should It Be in the Mod?

To make the model a bit nicer on the eyes, and fit better in the environment

It's a small nitpick, but I think it would look pretty nice

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This is based on GotV, but the design could be discussed.

**Comment by OzPayn** [comment]
Yeah I was actually going to request this as well, the top texture for the connection points does not look good imo and was more likely a limitation of the original development
