### ISSUE TITLE
Bug: Tempest causes game to crash upon Spawn

### ISSUE THREAD

**Issue by VoidHeart98** [The-Aether-Team/The-Aether-Genesis#142]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

45.0.64

### The Aether Genesis Version

0.0.1

### Client Log

https://gist.github.com/VoidHeart98/f24be964a04328aebee82935f1a049ff

### Crash Report (if applicable)

https://gist.github.com/VoidHeart98/ebb9dd4c3c071365a76176cd236e822b

### Steps to Reproduce

Crash happens every time a tempest Spawns, with the Spawn egg and spawning naturally 

### What You Expect To Happen

Tempest to spawn

### What Actually Happened

Crash

### Additional Details

![Screenshot 2023-05-28 162935](https://github.com/The-Aether-Team/The-Aether-Genesis/assets/134889446/e59faae1-508a-43e8-a3fe-d2fbf8915876)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The mod doesn't work with the latest beta, you have to download a circleci version of the aether.

**Comment by VoidHeart98** [comment]
Alrighty, Thank you!
