### ISSUE TITLE
Feature Request: Make items from the Continuum Bomb have a short-ish delay before they can be picked up

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#146]
### What Feature Types Apply to This Request?

Entity, Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

For the items spewed out of the continuum bomb to not be able to be picked up right away, but wait maybe about a second after they are launched out of the continuum bomb to be able to be picked up.

### Why Should It Be in the Mod?

Because if I remember correctly, it’s supposed to be an item that you migh throw into a crowd of players, and at the moment, if you stand at the same spot as the continuum bomb, you just collect all of the items, which means noone else gets any items if you’re in a crowd, which kindof defeats that purpose

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by KELETU66666** [comment]
got it, i'll go to fix it

**Comment by bconlon1** [comment]
Fixed in latest commits.
