### ISSUE TITLE
Feature Request: Directional Decoration Block changes

### ISSUE THREAD

**Issue by SteveJDM** [The-Aether-Team/The-Aether-Genesis#154]
### What Feature Types Apply to This Request?

Block

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

change the blocks: carved pillar carved, and holystone highlight to have more rotations. more similarly to pistons than logs. 

### Why Should It Be in the Mod?

it makes building a lot easier. right now it's fairly strange to build diagonally with pillars, and I think it just looks bad at the moment.
![2023-06-08_15 55 45](https://github.com/The-Aether-Team/The-Aether-Genesis/assets/83166955/dc6edfe7-2791-498c-ae82-a75f2e3a4bef)
![image](https://github.com/The-Aether-Team/The-Aether-Genesis/assets/83166955/375c175f-22db-49ec-8d3c-8340aee6dbea)

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Fixed in latest commit.
