### ISSUE TITLE
Feature Request: Labyrinth Ambience for the bronze dungeon

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#159]
### What Feature Types Apply to This Request?

Audio

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

The old Slider’s Labyrinth ambience from GoTV, but somehow applied to the bronze dungeon (maybe using the same kind of thing as how the game can tell when you enter a nether fortress in order to give you the achievement?)

### Why Should It Be in the Mod?

Because GoTV had it, and (at least in my opinion) it is one of the biggest parts of the GoTV dungeon atmosphere that made it have the vibe it did

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We'll probably only be adding ambience if we do the Slider's Labyrinth.
