### ISSUE TITLE
Feature Request: Boss music tracks

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#162]
### What Feature Types Apply to This Request?

Audio, Entity

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

The boss music tracks from GoTV for the Slider and minibosses

the music manager may need to be adjusted to stop any already playing music though (fading it out would be nice if that’s possible)
Also the music/sounds for when you defeat the minibosses or the slider would be nice too

### Why Should It Be in the Mod?

It was a feature in GoTV, and the music tracks sound awesome lol

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
May be handled elsewhere.
