### ISSUE TITLE
Feature Request: Configuration option to use smaller Zephyrs and Tempests

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#165]
### What Feature Types Apply to This Request?

Config, Entity

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

I didn’t see this idea in the issues tab, so I thought I’d make one for it
FEATURE REQUEST:
A configuration option (probably disabled by default) that readds the smaller Tempests and Zephyrs from GoTV. It would also be nice if the zephyrs were gold with the config option on as well, along with them *potentially* having their wind blowing attack as well, although it was a bit broken, but maybe they could have a more properly balanced (as in: less knockback, takes longer to charge up) version or something like that?

### Why Should It Be in the Mod?

Because it was in GoTV, and some people ~~*like me*~~ might prefer the smaller versions like they were in GoTV

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
My proposal for this is to include variation in Zephyrs and Tempests with the addon, including color variation for the Zephyr, and size variation for both mobs.

**Comment by bconlon1** [comment]
We'll likely at least have a color variation config for both blue and tan zephyrs.
