### ISSUE TITLE
Bug: Indicators for Dungeon Blocks are broken with Legacy Texture Pack

### ISSUE THREAD

**Issue by Builderdog841** [The-Aether-Team/The-Aether-Genesis#176]
### What Feature Types Apply to This Bug?

Art

### What Type of Bug Is This?

Design

### Forge Version

45.1.0

### The Aether Genesis Version

0.0.1

### Steps to Reproduce

Turn on Genesis Legacy Textures and then hold a Locked/ Boss Doorway/ Trapped/ Treasure Doorway block in your hand next to other ones.
See how the textures are glitched

### What You Expect To Happen

The Textures of the blocks to be normal

### What Actually Happened

The textures of Locked ones turned into Light Hellfirestones
The textures of Trapped ones turned into Bossdoorway Blocks
The textures of Bossdoorway Blocks turned into Divine Sentry Stone
The textures of Treasuredoorway Blocks turned into Dthe glow texture of a Songstone from Lost Content

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
I swear this bug has appeared in the past but a fix was made, a similar thing might be happening here that might need to be fixed.

**Comment by bconlon1** [comment]
The issue has to be coming from the render types in some way, I'll have to use the debugger to figure out why the textures get jumbled.
