### ISSUE TITLE
Feature Request: Tiny zephyrs config option

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#198]
### What Feature Types Apply to This Request?

Config, Entity

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

A config to make the zephyrs into the tiny guys they were in gotv

![the fnuuy](https://static.wikia.nocookie.net/aether_gamepedia_en/images/b/bc/2015-06-08_12.18.25.png/revision/latest/scale-to-width-down/250?cb=20180126122833)

these things were always really funny to me in gotv lol

something that could also potentially be a good idea for them is *maybe* replacing the wind gust attack with just a less powerful version of the current zephyr snowball? if the original attack is too wonky and/or broken at least

maybe the blue ones could be the rarer ones with this config, and be slightly bigger? maybe 1.5x the size idk

### Why Should It Be in the Mod?

since that's the way they were in gotv, it'd be nice to have a config to have them like the original ones

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Zephyrs have now been made slightly smaller
