### ISSUE TITLE
Bug: Skyroot Chest Mimics do not have jade compat stuff

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#199]
### What Feature Types Apply to This Bug?

Entity, Gui, System

### What Type of Bug Is This?

None

### Forge Version

47.1.70

### The Aether Genesis Version

6343dd5

### Is This Bug a Conflict With Another Mod?

Jade (sorta)

### Steps to Reproduce

1: Use the Jade mod
2: Look at a Skyroot Chest Mimic (the block)

### What You Expect To Happen

It would display as a Skyroot Chest without generated loot (similar to chest mimics from the base mod)

### What Actually Happened

It displayed as a Skyroot Chest Mimic, revealing the fact that it is not a regular chest

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
added
