### ISSUE TITLE
Feature Request: [Idea] Retexturing + Renaming locked dungeon blocks into divine instead of using separate blocks for divine stones

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#202]
### What Feature Types Apply to This Request?

Block

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether Genesis.

### What Is Your Feature Request?

so, the divine stones in gotv were basically just the replacements for locked blocks, and were practically identical to them apart from their name and texture, my idea is that genesis should modify the base mod’s locked blocks like this, renaming them and redirecting their textures to genesis’s divine stone textures

I was also able to successfully replicate this idea inside a resource pack a while ago too, so it should be able to be done fairly easily with a name change and a model change (so it gets directed to the right texture)

### Why Should It Be in the Mod?

to decrease unnecessary extra blocks, plus also for consistency since in gotv the divine stones were literally just reskinned renamed replacements for the locked stones

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in Aether II Genesis of the Void, or improves parity between The Aether Genesis and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
we're probably going to keep the divine blocks separate, as they're another possible building block they're not exactly unnecessary.
